import { Theme, IconType } from "@/typings/editor";
import { convertToShikiTheme } from "../themes/shared";

export const clerk: Theme = {
  id: "clerk",
  name: "Clerk",
  background: {
    from: "#000000",
    to: "#000000",
  },
  icon: { type: IconType.IMAGE, source: "/editor/assets/clerk/logo.svg" },
  partner: true,
  group: "Brands",
  lineNumbers: true,
  font: "geist-mono",
  syntax: {
    light: convertToShikiTheme({
      foreground: "#131316",
      constant: "#22c543",
      string: "#00aee3",
      comment: "#9394a1",
      keyword: "#6c47ff",
      parameter: "#22c543",
      function: "#6c47ff",
      stringExpression: "#00aee3",
      punctuation: "#747686",
      link: "#22c543",
      number: "#22c543",
      property: "#22c543",
      highlight: "#00aee313",
      highlightHover: "#00aee306",
      highlightBorder: "#00000000",
      diffInserted: "#22c543",
      diffDeleted: "#FF605E",
    }),
    dark: convertToShikiTheme({
      foreground: "#ffffff",
      constant: "#86ef9b",
      string: "#5de3ff",
      comment: "#9394a1",
      keyword: "#bab1ff",
      parameter: "#86ef9b",
      function: "#bab1ff",
      stringExpression: "#5de3ff",
      punctuation: "#b7b8c2",
      link: "#86ef9b",
      number: "#86ef9b",
      property: "#86ef9b",
      highlight: "#5de3ff1a",
      highlightHover: "#5de3ff0d",
      highlightBorder: "#00000000",
      diffInserted: "#86ef9b",
      diffDeleted: "#E17271",
    }),
  },
};
