import { Theme } from "@/typings/editor";

/**
 * All 66 Shiki bundled themes registered as CuteCode themes.
 * These use Shiki's native highlighting — syntax colors come
 * directly from Shiki (not from CSS variables), so the `syntax`
 * object is intentionally empty.
 *
 * The `id` field MUST match the Shiki bundled theme key exactly.
 */

const shikiThemes: Record<string, Theme> = {
  andromeeda: {
    id: "andromeeda",
    name: "Andromeeda",
    background: { from: "#23262E", to: "#1a1d24" },
    group: "System",
    syntax: { dark: {} },
  },
  "aurora-x": {
    id: "aurora-x",
    name: "Aurora X",
    background: { from: "#07090F", to: "#0d1020" },
    group: "System",
    syntax: { dark: {} },
  },
  "ayu-dark": {
    id: "ayu-dark",
    name: "Ayu Dark",
    background: { from: "#10141c", to: "#0d1018" },
    group: "System",
    syntax: { dark: {} },
  },
  "ayu-light": {
    id: "ayu-light",
    name: "Ayu Light",
    background: { from: "#fcfcfc", to: "#eaeaea" },
    group: "System",
    syntax: { light: {} },
  },
  "ayu-mirage": {
    id: "ayu-mirage",
    name: "Ayu Mirage",
    background: { from: "#242936", to: "#1c2030" },
    group: "System",
    syntax: { dark: {} },
  },
  "catppuccin-frappe": {
    id: "catppuccin-frappe",
    name: "Catppuccin Frappé",
    background: { from: "#303446", to: "#232634" },
    group: "System",
    syntax: { dark: {} },
  },
  "catppuccin-latte": {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    background: { from: "#eff1f5", to: "#dce0e8" },
    group: "System",
    syntax: { light: {} },
  },
  "catppuccin-macchiato": {
    id: "catppuccin-macchiato",
    name: "Catppuccin Macchiato",
    background: { from: "#24273a", to: "#181926" },
    group: "System",
    syntax: { dark: {} },
  },
  "catppuccin-mocha": {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    background: { from: "#1e1e2e", to: "#11111b" },
    group: "System",
    syntax: { dark: {} },
  },
  "dark-plus": {
    id: "dark-plus",
    name: "Dark+",
    background: { from: "#1E1E1E", to: "#141414" },
    group: "System",
    syntax: { dark: {} },
  },
  dracula: {
    id: "dracula",
    name: "Dracula",
    background: { from: "#282A36", to: "#1e202a" },
    group: "System",
    syntax: { dark: {} },
  },
  "dracula-soft": {
    id: "dracula-soft",
    name: "Dracula Soft",
    background: { from: "#282A36", to: "#1e202a" },
    group: "System",
    syntax: { dark: {} },
  },
  "everforest-dark": {
    id: "everforest-dark",
    name: "Everforest Dark",
    background: { from: "#2d353b", to: "#232a2e" },
    group: "System",
    syntax: { dark: {} },
  },
  "everforest-light": {
    id: "everforest-light",
    name: "Everforest Light",
    background: { from: "#fdf6e3", to: "#f0e9d2" },
    group: "System",
    syntax: { light: {} },
  },
  "github-dark": {
    id: "github-dark",
    name: "GitHub Dark",
    background: { from: "#24292e", to: "#1b1f23" },
    group: "System",
    syntax: { dark: {} },
  },
  "github-dark-default": {
    id: "github-dark-default",
    name: "GitHub Dark Default",
    background: { from: "#0d1117", to: "#010409" },
    group: "System",
    syntax: { dark: {} },
  },
  "github-dark-dimmed": {
    id: "github-dark-dimmed",
    name: "GitHub Dark Dimmed",
    background: { from: "#22272e", to: "#1c2128" },
    group: "System",
    syntax: { dark: {} },
  },
  "github-dark-high-contrast": {
    id: "github-dark-high-contrast",
    name: "GitHub Dark High Contrast",
    background: { from: "#0a0c10", to: "#000000" },
    group: "System",
    syntax: { dark: {} },
  },
  "github-light": {
    id: "github-light",
    name: "GitHub Light",
    background: { from: "#ffffff", to: "#f0f0f0" },
    group: "System",
    syntax: { light: {} },
  },
  "github-light-default": {
    id: "github-light-default",
    name: "GitHub Light Default",
    background: { from: "#ffffff", to: "#f0f0f0" },
    group: "System",
    syntax: { light: {} },
  },
  "github-light-high-contrast": {
    id: "github-light-high-contrast",
    name: "GitHub Light High Contrast",
    background: { from: "#ffffff", to: "#f0f0f0" },
    group: "System",
    syntax: { light: {} },
  },
  "gruvbox-dark-hard": {
    id: "gruvbox-dark-hard",
    name: "Gruvbox Dark Hard",
    background: { from: "#1d2021", to: "#141617" },
    group: "System",
    syntax: { dark: {} },
  },
  "gruvbox-dark-medium": {
    id: "gruvbox-dark-medium",
    name: "Gruvbox Dark Medium",
    background: { from: "#282828", to: "#1d2021" },
    group: "System",
    syntax: { dark: {} },
  },
  "gruvbox-dark-soft": {
    id: "gruvbox-dark-soft",
    name: "Gruvbox Dark Soft",
    background: { from: "#32302f", to: "#282828" },
    group: "System",
    syntax: { dark: {} },
  },
  "gruvbox-light-hard": {
    id: "gruvbox-light-hard",
    name: "Gruvbox Light Hard",
    background: { from: "#f9f5d7", to: "#ebdbb2" },
    group: "System",
    syntax: { light: {} },
  },
  "gruvbox-light-medium": {
    id: "gruvbox-light-medium",
    name: "Gruvbox Light Medium",
    background: { from: "#fbf1c7", to: "#ebdbb2" },
    group: "System",
    syntax: { light: {} },
  },
  "gruvbox-light-soft": {
    id: "gruvbox-light-soft",
    name: "Gruvbox Light Soft",
    background: { from: "#f2e5bc", to: "#ebdbb2" },
    group: "System",
    syntax: { light: {} },
  },
  horizon: {
    id: "horizon",
    name: "Horizon",
    background: { from: "#1C1E26", to: "#16181f" },
    group: "System",
    syntax: { dark: {} },
  },
  "horizon-bright": {
    id: "horizon-bright",
    name: "Horizon Bright",
    background: { from: "#FDF0ED", to: "#f0e0db" },
    group: "System",
    syntax: { light: {} },
  },
  houston: {
    id: "houston",
    name: "Houston",
    background: { from: "#17191e", to: "#0e1014" },
    group: "System",
    syntax: { dark: {} },
  },
  "kanagawa-dragon": {
    id: "kanagawa-dragon",
    name: "Kanagawa Dragon",
    background: { from: "#181616", to: "#0d0c0c" },
    group: "System",
    syntax: { dark: {} },
  },
  "kanagawa-lotus": {
    id: "kanagawa-lotus",
    name: "Kanagawa Lotus",
    background: { from: "#F2ECBC", to: "#ddd8a8" },
    group: "System",
    syntax: { light: {} },
  },
  "kanagawa-wave": {
    id: "kanagawa-wave",
    name: "Kanagawa Wave",
    background: { from: "#1F1F28", to: "#16161d" },
    group: "System",
    syntax: { dark: {} },
  },
  laserwave: {
    id: "laserwave",
    name: "Laserwave",
    background: { from: "#27212e", to: "#1c1722" },
    group: "System",
    syntax: { dark: {} },
  },
  "light-plus": {
    id: "light-plus",
    name: "Light+",
    background: { from: "#FFFFFF", to: "#f0f0f0" },
    group: "System",
    syntax: { light: {} },
  },
  "material-theme": {
    id: "material-theme",
    name: "Material Theme",
    background: { from: "#263238", to: "#1c2529" },
    group: "System",
    syntax: { dark: {} },
  },
  "material-theme-darker": {
    id: "material-theme-darker",
    name: "Material Theme Darker",
    background: { from: "#212121", to: "#171717" },
    group: "System",
    syntax: { dark: {} },
  },
  "material-theme-lighter": {
    id: "material-theme-lighter",
    name: "Material Theme Lighter",
    background: { from: "#FAFAFA", to: "#eeeeee" },
    group: "System",
    syntax: { light: {} },
  },
  "material-theme-ocean": {
    id: "material-theme-ocean",
    name: "Material Theme Ocean",
    background: { from: "#0F111A", to: "#090b10" },
    group: "System",
    syntax: { dark: {} },
  },
  "material-theme-palenight": {
    id: "material-theme-palenight",
    name: "Material Theme Palenight",
    background: { from: "#292D3E", to: "#1e2132" },
    group: "System",
    syntax: { dark: {} },
  },
  "min-dark": {
    id: "min-dark",
    name: "Min Dark",
    background: { from: "#1f1f1f", to: "#141414" },
    group: "System",
    syntax: { dark: {} },
  },
  "min-light": {
    id: "min-light",
    name: "Min Light",
    background: { from: "#ffffff", to: "#f0f0f0" },
    group: "System",
    syntax: { light: {} },
  },
  monokai: {
    id: "monokai",
    name: "Monokai",
    background: { from: "#272822", to: "#1e201a" },
    group: "System",
    syntax: { dark: {} },
  },
  "night-owl": {
    id: "night-owl",
    name: "Night Owl",
    background: { from: "#011627", to: "#010f1a" },
    group: "System",
    syntax: { dark: {} },
  },
  "night-owl-light": {
    id: "night-owl-light",
    name: "Night Owl Light",
    background: { from: "#FBFBFB", to: "#ebebeb" },
    group: "System",
    syntax: { light: {} },
  },
  nord: {
    id: "nord",
    name: "Nord",
    background: { from: "#2e3440", to: "#242933" },
    group: "System",
    syntax: { dark: {} },
  },
  "one-dark-pro": {
    id: "one-dark-pro",
    name: "One Dark Pro",
    background: { from: "#282c34", to: "#21252b" },
    group: "System",
    syntax: { dark: {} },
  },
  "one-light": {
    id: "one-light",
    name: "One Light",
    background: { from: "#FAFAFA", to: "#eeeeee" },
    group: "System",
    syntax: { light: {} },
  },
  plastic: {
    id: "plastic",
    name: "Plastic",
    background: { from: "#21252B", to: "#181b20" },
    group: "System",
    syntax: { dark: {} },
  },
  poimandres: {
    id: "poimandres",
    name: "Poimandres",
    background: { from: "#1b1e28", to: "#13151e" },
    group: "System",
    syntax: { dark: {} },
  },
  red: {
    id: "red",
    name: "Red",
    background: { from: "#390000", to: "#1f0000" },
    group: "System",
    syntax: { dark: {} },
  },
  "rose-pine": {
    id: "rose-pine",
    name: "Rosé Pine",
    background: { from: "#191724", to: "#110f1a" },
    group: "System",
    syntax: { dark: {} },
  },
  "rose-pine-dawn": {
    id: "rose-pine-dawn",
    name: "Rosé Pine Dawn",
    background: { from: "#faf4ed", to: "#ede8e0" },
    group: "System",
    syntax: { light: {} },
  },
  "rose-pine-moon": {
    id: "rose-pine-moon",
    name: "Rosé Pine Moon",
    background: { from: "#232136", to: "#18162b" },
    group: "System",
    syntax: { dark: {} },
  },
  "slack-dark": {
    id: "slack-dark",
    name: "Slack Dark",
    background: { from: "#222222", to: "#191919" },
    group: "System",
    syntax: { dark: {} },
  },
  "slack-ochin": {
    id: "slack-ochin",
    name: "Slack Ochin",
    background: { from: "#ffffff", to: "#f0f0f0" },
    group: "System",
    syntax: { light: {} },
  },
  "snazzy-light": {
    id: "snazzy-light",
    name: "Snazzy Light",
    background: { from: "#FAFBFC", to: "#eaebec" },
    group: "System",
    syntax: { light: {} },
  },
  "solarized-dark": {
    id: "solarized-dark",
    name: "Solarized Dark",
    background: { from: "#002B36", to: "#001e27" },
    group: "System",
    syntax: { dark: {} },
  },
  "solarized-light": {
    id: "solarized-light",
    name: "Solarized Light",
    background: { from: "#FDF6E3", to: "#ede5d0" },
    group: "System",
    syntax: { light: {} },
  },
  "synthwave-84": {
    id: "synthwave-84",
    name: "Synthwave '84",
    background: { from: "#262335", to: "#1a1726" },
    group: "System",
    syntax: { dark: {} },
  },
  "tokyo-night": {
    id: "tokyo-night",
    name: "Tokyo Night",
    background: { from: "#1a1b26", to: "#13141f" },
    group: "System",
    syntax: { dark: {} },
  },
  vesper: {
    id: "vesper",
    name: "Vesper",
    background: { from: "#101010", to: "#080808" },
    group: "System",
    syntax: { dark: {} },
  },
  "vitesse-black": {
    id: "vitesse-black",
    name: "Vitesse Black",
    background: { from: "#000000", to: "#111111" },
    group: "System",
    syntax: { dark: {} },
  },
  "vitesse-dark": {
    id: "vitesse-dark",
    name: "Vitesse Dark",
    background: { from: "#121212", to: "#0a0a0a" },
    group: "System",
    syntax: { dark: {} },
  },
  "vitesse-light": {
    id: "vitesse-light",
    name: "Vitesse Light",
    background: { from: "#ffffff", to: "#f0f0f0" },
    group: "System",
    syntax: { light: {} },
  },
};

export default shikiThemes;
