import { Theme, IconType } from "@/typings/editor";
import { convertToShikiTheme } from "../themes/shared";

export const prisma: Theme = {
  id: "prisma",
  name: "Prisma",
  background: {
    from: "#000",
    to: "#000",
  },
  icon: { type: IconType.IMAGE, source: "/editor/assets/prisma/logo.svg" },
  partner: true,
  group: "Brands",
  lineNumbers: false,
  syntax: {
    light: convertToShikiTheme({
      foreground: "#1A202C",
      constant: "#5A67D8",
      string: "#16A394",
      comment: "#718096",
      keyword: "#16A394",
      parameter: "#805AD5",
      function: "#5A67D8",
      stringExpression: "#16A394",
      punctuation: "#1A202C",
      link: "#5A67D8",
      number: "#16A394",
      property: "#16A394",
      highlight: "#16a39528",
      highlightHover: "#16a3950e",
      highlightBorder: "#16A394",
      diffInserted: "#16A394",
      diffDeleted: "#FF605E",
    }),
    dark: convertToShikiTheme({
      foreground: "#ffffff",
      constant: "#7F9CF5",
      string: "#71E8DF",
      comment: "#718096",
      keyword: "#71E8DF",
      parameter: "#71E8DF",
      function: "#7F9CF5",
      stringExpression: "#71E8DF",
      punctuation: "#FFFFFF",
      link: "#7F9CF5",
      number: "#71E8DF",
      property: "#71E8DF",
      highlight: "#71e8de2e",
      highlightHover: "#71e8de1b",
      highlightBorder: "#71E8DF",
      diffInserted: "#16A394",
      diffDeleted: "#FC8280",
    }),
  },
};
