import { Theme } from "@/typings/editor";
import { convertToShikiTheme } from "../shared";

export const supabase: Theme = {
  id: "supabase",
  name: "Supabase",
  background: {
    from: "#121212",
    to: "#121212",
  },
  icon: "/editor/assets/supabase.svg",
  partner: true,
  group: "Brands",
  lineNumbers: true,
  font: "jetbrains-mono",
  syntax: {
    light: convertToShikiTheme({
      foreground: "#525252",
      constant: "#15593b",
      string: "#f1a10d",
      comment: "#7e7e7e",
      keyword: "#6b35dc",
      parameter: "#525252",
      function: "#15593b",
      stringExpression: "#f1a10d",
      punctuation: "#a0a0a0",
      link: "#525252",
      number: "#525252",
      property: "#15593b",
      highlight: "oklch(0.88 0.22 153.28 / 0.12)",
      highlightHover: "oklch(0.88 0.22 153.28 / 0.06)",
      highlightBorder: "#009a55",
    }),
    dark: convertToShikiTheme({
      foreground: "#ffffff",
      constant: "#3ecf8e",
      string: "#ffcda1",
      comment: "#7e7e7e",
      keyword: "#bda4ff",
      parameter: "#ffffff",
      function: "#3ecf8e",
      stringExpression: "#ffcda1",
      punctuation: "#ffffff",
      link: "#ffffff",
      number: "#ededed",
      property: "#3ecf8e",
      highlight: "#232323",
      highlightHover: "#1D1D1D",
      highlightBorder: "#383838",
      diffInserted: "#3ecf8e",
      diffDeleted: "#F06A50",
    }),
  },
};
