import { Theme } from "@/typings/editor";
import { convertToShikiTheme, MintlifyLogo, MintlifyLogoUrl } from "./shared";

export const mintlify: Theme = {
    id: "mintlify",
    name: "Mintlify",
    background: {
      from: "#000",
      to: "#000",
    },
    icon: MintlifyLogo,
    iconUrl: MintlifyLogoUrl,
    partner: true,
    group: "Brands",
    syntax: {
      light: convertToShikiTheme({
        foreground: "#171717",
        constant: "#0d9373",
        string: "#171717",
        comment: "#707070",
        keyword: "#0d548f",
        parameter: "#0576b7",
        function: "#0576b7",
        stringExpression: "#d55d2e",
        punctuation: "#808080",
        link: "#4aab15",
        number: "#4aab15",
        property: "#4aab15",
        highlight: "#dfbe5b3a",
        highlightHover: "#dfbe5b1b",
        highlightBorder: "#e8bc39",
        diffInserted: "#0d9373",
        diffDeleted: "#DC2625",
      }),
      dark: convertToShikiTheme({
        foreground: "#F3F7F6",
        constant: "#4ec9b0",
        string: "#F3F7F6",
        comment: "#707070",
        keyword: "#569cd6",
        parameter: "#9cdcfe",
        function: "#9cdcfe",
        stringExpression: "#ce9178",
        punctuation: "#808080",
        link: "#b5cea8",
        number: "#b5cea8",
        property: "#b5cea8",
        highlight: "rgb(131 114 55 / 30%)",
        highlightHover: "rgb(131 114 55 / 15%)",
        highlightBorder: "#f7d87c",
        diffInserted: "#4ec9b0",
        diffDeleted: "#E17271",
      }),
    },
  };
