import { Theme } from "@/typings/editor";
import { convertToShikiTheme, NuxtLogo, NuxtLogoUrl } from "./shared";

export const nuxt: Theme = {
    id: "nuxt",
    name: "Nuxt",
    background: {
      from: "#292D3E",
      to: "#292D3E",
    },
    icon: NuxtLogo,
    iconUrl: NuxtLogoUrl,
    font: "geist-mono",
    partner: true,
    group: "Brands",
    lineNumbers: true,
    syntax: {
      light: convertToShikiTheme({
        foreground: "#90A4AE",
        constant: "#39ADB5",
        string: "#91B859",
        comment: "#90A4AE",
        keyword: "#39ADB5",
        parameter: "#90A4AE",
        function: "#6182B8",
        stringExpression: "#E53935",
        punctuation: "#39ADB5",
        link: "#80CBC4",
        number: "#F76D47",
        property: "#E53935",
        highlight: "rgba(128, 203, 196, 0.25)",
        highlightHover: "rgba(128, 203, 196, 0.15)",
        highlightBorder: "#80CBC4",
        diffInserted: "#91B859",
        diffDeleted: "#E53935",
      }),
      dark: convertToShikiTheme({
        foreground: "#babed8",
        constant: "#BABED8",
        string: "#C3E88D",
        comment: "#676E95",
        keyword: "#C793EA",
        parameter: "#babed8",
        function: "#82AAFF",
        stringExpression: "#f07178",
        punctuation: "#89DDFF",
        link: "#80CBC4",
        number: "#F78C6C",
        property: "#f07178",
        highlight: "rgba(113, 124, 180, 0.31)",
        highlightHover: "rgba(113, 124, 180, 0.2)",
        highlightBorder: "#80CBC4",
        diffInserted: "#C3E88D",
        diffDeleted: "#f07178",
      }),
    },
  };
