import { Theme } from "@/typings/editor";
import { convertToShikiTheme, OpenAiLogo, OpenAiLogoUrl } from "./shared";

export const openai: Theme = {
    id: "openai",
    name: "OpenAI",
    background: {
      from: "#000",
      to: "#000",
    },
    icon: OpenAiLogo,
    iconUrl: OpenAiLogoUrl,
    partner: true,
    group: "AI",
    font: "soehne-mono",
    lineNumbers: true,
    syntax: {
      light: convertToShikiTheme({
        foreground: "#171717",
        constant: "#DF3079",
        string: "#171717",
        comment: "hsla(240, 12%, 71%, 1)",
        keyword: "#2E95D3",
        parameter: "#ededed",
        function: "#00A67D",
        stringExpression: "#00a67d",
        punctuation: "#171717",
        link: "#F22C3D",
        number: "#e9950c",
        property: "#F22C3D",
        highlight: "rgba(0,0,0,0.02)",
        highlightHover: "rgba(0,0,0,0.015)",
        diffInserted: "#00A67D",
        diffDeleted: "#F22C3D",
      }),
      dark: convertToShikiTheme({
        foreground: "#fff",
        constant: "#df3079",
        string: "#fff",
        comment: "rgba(255,255,255,0.4)",
        keyword: "#2E95D3",
        parameter: "#fff",
        function: "#00A67D",
        stringExpression: "#00A67D",
        punctuation: "#fff",
        link: "#F22C3D",
        number: " #e9950c",
        property: "#F22C3D",
        highlight: "rgba(255, 255, 255, 0.05)",
        highlightHover: "rgba(255, 255, 255, 0.03)",
        diffInserted: "#00A67D",
        diffDeleted: "#F22C3D",
      }),
    },
  };
