import { Theme } from "@/typings/editor";
import { convertToShikiTheme, ResendLogo, ResendLogoUrl } from "./shared";

export const resend: Theme = {
    id: "resend",
    name: "Resend",
    background: {
      from: "#B1B1B1",
      to: "#181818",
    },
    icon: ResendLogo,
    iconUrl: ResendLogoUrl,
    font: "commit-mono",
    partner: true,
    group: "Brands",
    syntax: {
      light: convertToShikiTheme({
        foreground: "#111111",
        constant: "#666666",
        parameter: "#666666",
        stringExpression: "#666666",
        keyword: "#666666",
        function: "#111111",
        punctuation: "#666666",
        string: "#666666",
        comment: "#999999",
        link: "#666666",
        number: "#111111",
        property: "#666666",
        diffInserted: "#666666",
        diffDeleted: "#666666",
      }),
      dark: convertToShikiTheme({
        foreground: "#ffffff",
        constant: "#a7a7a7",
        parameter: "#a7a7a7",
        stringExpression: "#a7a7a7",
        keyword: "#a7a7a7",
        function: "#ffffff",
        punctuation: "#a7a7a7",
        string: "#a7a7a7",
        comment: "#666666",
        link: "#a7a7a7",
        number: "#ffffff",
        property: "#a7a7a7",
        diffInserted: "#a7a7a7",
        diffDeleted: "#a7a7a7",
      }),
    },
  };
